stages:
- test
- pages

# Execute Unit-Tests
Unit Testing:
  stage: test
  image: node:18-slim
  script: 
    # build
    - npm i
    - npm run-script test

# Static Application Security Testing
include:
- template: Security/SAST.gitlab-ci.yml

# Publish Demo-Application to GitLab-Pages
pages:
  stage: pages
  image: node:18-slim
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  before_script:
    - apt update && apt -y upgrade && apt install -y brotli
  script: 
    # build
    - npm i
    - npm run-script build
    # Compress files
    - find public -type f -regex '.*\.\(html\|css\|json\)' -exec brotli -k -f {} \;
    - find public -type f -regex '.*\.\(html\|css\|json\)' -exec gzip -k -f {} \;
    # Create a instance for a sample cartoriviera instance
    - cp -R public cartoriviera && mv cartoriviera public/
    - rm public/cartoriviera/config.json 
    - cp public/config.cartoriviera.json public/cartoriviera/config.json

  artifacts:
    paths:
      # Directory needs to be named 'public' for GitLab Pages
      - public
