stages:
  - test
  - build
  - docker-build
  - pages
  - scan

#unitests:
#  stage: test
#  image: node:18-slim
#  
#  script: 
#    # build
#    - npm i
#    - npm run test

npm-audit:
  stage: test
  image: node:18-slim
  
  script: 
    # build
    - npm i
    - npm audit
    - npm audit signatures

# Static Application Security Testing
include:
- template: Security/SAST.gitlab-ci.yml

# Build the application
build:
  stage: build
  image: node:18-slim

  before_script:
    - apt update && apt -y install jq brotli
  script: 
    - npm i --omit=dev
    - npm run build
    # List all dependencies
    - npm list --all --omit=dev
    # Generate Version Number
    - version=$(jq -r '.version' package.json)
    - echo '{"version":"'$version'", "build":"'$CI_PIPELINE_ID'", "date":"'$(date +'%d/%m/%Y')'"}' > public/about.json
    # Compress all files
    - find public -type f -regex '.*\.\(html\|css\|js\|json\)' -exec brotli -k -f {} \;
    - find public -type f -regex '.*\.\(html\|css\|js\|json\)' -exec gzip -k -f {} \;
  artifacts:
    paths:
      - public

docker-build:
  stage: docker-build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

  script: 
    # build
    - docker build -t geogirafe/viewer -f buildtools/Dockerfile .
    # push
    - docker push geogirafe/viewer


# Publish Demo-Application to GitLab-Pages
pages:
  stage: pages
  image: debian:stable-slim
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  before_script:
    - apt update && apt install -y brotli curl
  script: 
    - mkdir -p public/Mock
    - mkdir release
    # Create a instance for a sample mapbs instance
    - cp -R public mapbs && mv mapbs release/
    - cp demo/config.mapbs.json release/mapbs/config.json
    - gzip -k -f release/mapbs/config.json
    - brotli -k -f release/mapbs/config.json
    # Create a instance for a sample cartoriviera instance
    - cp -R public cartoriviera && mv cartoriviera release/
    - cp demo/config.cartoriviera.json release/cartoriviera/config.json
    - gzip -k -f release/cartoriviera/config.json
    - brotli -k -f release/cartoriviera/config.json
    # Create a instance for a sample cartolacote instance
    - cp -R public cartolacote && mv cartolacote release/
    - cp demo/config.cartolacote.json release/cartolacote/config.json
    - gzip -k -f release/cartolacote/config.json
    - brotli -k -f release/cartolacote/config.json
    # Create a instance for a sample mapnv instance
    - cp -R public mapnv && mv mapnv release/
    - cp demo/config.mapnv.json release/mapnv/config.json
    - gzip -k -f release/mapnv/config.json
    - brotli -k -f release/mapnv/config.json
    # Create a instance for a sample sitn instance
    - cp -R public sitn && mv sitn release/
    - cp demo/config.sitn.json release/sitn/config.json
    - gzip -k -f release/sitn/config.json
    - brotli -k -f release/sitn/config.json
    # Create a instance for a sample schwyz instance
    - cp -R public schwyz && mv schwyz release/
    - cp demo/config.schwyz.json release/schwyz/config.json
    - gzip -k -f release/schwyz/config.json
    - brotli -k -f release/schwyz/config.json
    # Create a instance for a sample geogr instance
    - cp -R public geogr && mv geogr release/
    - cp demo/config.geogr.json release/geogr/config.json
    - gzip -k -f release/geogr/config.json
    - brotli -k -f release/geogr/config.json
    # Create a instance for a sample lie instance
    - cp -R public lie && mv lie release/
    - cp demo/config.lie.json release/lie/config.json
    - gzip -k -f release/lie/config.json
    - brotli -k -f release/lie/config.json
    
    # Rename the relase directory to public
    - rm -Rf public && mv release public

    # Copy demo index page
    - cp demo/index.html public/
    - cp -R demo/static public/

    # Wget themes.json to improve performance on demo instance
    # (this does not work for cartoriviera.ch, it seems to be blocked)
    # MapBS
    - curl "https://map.geo.bs.ch/themes?background=background&interface=desktop" --output public/mapbs/Mock/themes.json
    - gzip -k -f public/mapbs/Mock/themes.json
    - brotli -k -f public/mapbs/Mock/themes.json
    # Cartolacote
    - curl "https://map.cartolacote.ch/themes?background=background&interface=desktop" --output public/cartolacote/Mock/themes.json
    - gzip -k -f public/cartolacote/Mock/themes.json
    - brotli -k -f public/cartolacote/Mock/themes.json
    # MapNV
    - curl "https://mapnv.ch/themes?background=background&interface=desktop" --output public/mapnv/Mock/themes.json
    - gzip -k -f public/mapnv/Mock/themes.json
    - brotli -k -f public/mapnv/Mock/themes.json
    # SITN
    - curl "https://sitn.ne.ch/themes?background=desktop_background&interface=desktop" --output public/sitn/Mock/themes.json
    - curl "https://sitn.ne.ch/printproxy/capabilities.json" --output public/sitn/Mock/capabilities.json
    - gzip -k -f public/sitn/Mock/themes.json public/sitn/Mock/capabilities.json
    - brotli -k -f public/sitn/Mock/themes.json public/sitn/Mock/capabilities.json
    # Schwyz
    - curl "https://map.geo.sz.ch/themes?background=background&interface=desktop" --output public/schwyz/Mock/themes.json
    - gzip -k -f public/schwyz/Mock/themes.json
    - brotli -k -f public/schwyz/Mock/themes.json
    # GeoGR
    - curl "https://edit.geo.gr.ch/themes?background=background&interface=desktop" --output public/geogr/Mock/themes.json
    - curl "https://edit.geo.gr.ch/static-ngeo/build/de.json" --output public/geogr/Mock/de.json
    - curl "https://edit.geo.gr.ch/printproxy/capabilities.json" --output public/geogr/Mock/capabilities.json
    - gzip -k -f public/geogr/Mock/themes.json public/geogr/Mock/de.json public/geogr/Mock/capabilities.json
    - brotli -k -f public/geogr/Mock/themes.json public/geogr/Mock/de.json public/geogr/Mock/capabilities.json
    # Liechtenstein
    - curl "https://map.geo.llv.li/themes?background=background&interface=desktop" --output public/lie/Mock/themes.json
    - curl "https://map.geo.llv.li/static/X/de.json" --output public/lie/Mock/de.json
    - curl "https://map.geo.llv.li/printproxy/capabilities.json" --output public/lie/Mock/capabilities.json
    - gzip -k -f public/lie/Mock/themes.json public/lie/Mock/de.json public/lie/Mock/capabilities.json
    - brotli -k -f public/lie/Mock/themes.json public/lie/Mock/de.json public/lie/Mock/capabilities.json

  artifacts:
    paths:
      # Directory needs to be named 'public' for GitLab Pages
      - public

zap-baseline-scan:
  stage: scan
  image: owasp/zap2docker-stable
  dependencies:
    - pages
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  script:
    - mkdir /zap/wrk
    # TODO REG: By default, all alerts are reported as warnings.
    # TODO REG: Configure which ones should be reported as "fail"
    - /zap/zap-baseline.py -j -I -t https://geogirafe.paloo.fr/mapbs/ -r report.html -w report.md -x report.xml -J report.json
  artifacts:
    paths:
      # Directory needs to be named 'public' for GitLab Pages
      - /zap/wrk
