stages:
  - test
  - build
  - docker-build
  - pages

# Execute Unit-Tests
Unit Testing:
  stage: test
  image: node:18-slim
  script: 
    # build
    - npm i
    - npm run-script test

# Static Application Security Testing
include:
- template: Security/SAST.gitlab-ci.yml

# Build the application
build:
  stage: build
  image: node:18-slim

  before_script:
    - apt update && apt -y upgrade
  script: 
    - npm i
    - npm run-script build

  artifacts:
    paths:
      - public

docker-build:
  stage: docker-build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

  script: 
    # build
    - docker build -t geogirafe/viewer -f buildtools/Dockerfile .
    # push
    - docker push geogirafe/viewer


# Publish Demo-Application to GitLab-Pages
pages:
  stage: pages
  image: debian:stable-slim
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

  before_script:
    - apt update && apt -y upgrade && apt install -y brotli
  script: 
    # Create a instance for a sample cartoriviera instance
    - cp -R public cartoriviera && mv cartoriviera public/
    - rm public/cartoriviera/config.json 
    - cp public/config.cartoriviera.json public/cartoriviera/config.json
    # Compress all files
    - find public -type f -regex '.*\.\(html\|css\|json\)' -exec brotli -k -f {} \;
    - find public -type f -regex '.*\.\(html\|css\|json\)' -exec gzip -k -f {} \;

  artifacts:
    paths:
      # Directory needs to be named 'public' for GitLab Pages
      - public
