sonar.projectKey=geogirafe_gg-viewer
sonar.organization=geogirafe

sonar.projectName=GeoGirafe Viewer
sonar.projectVersion=0.2

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src/

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8