sonar.projectKey=geogirafe_gg-viewer
sonar.organization=geogirafe

sonar.projectName=GeoGirafe Viewer
sonar.projectVersion=0.2

# Deactivate code coverage tests for the moment
# TODO REG : Check for which code we want to activate the coverage when the tests are ready
sonar.coverage.exclusions="**/**"
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# Configuration example : https://docs.sonarsource.com/sonarqube/latest/project-administration/analysis-scope/#example-2
sonar.sources=src/
sonar.exclusions=src/static/lib/**,src/**/*.spec.ts
#sonar.tests=src/
#sonar.test.inclusions=src/**/*.spec.ts
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8