import DragManager from '../../components/treeview/tools/dragmanager';
import ApplicationLifeCycleManager from '../app/lifecyclemanager';
import AuthManager from '../auth/authmanager';
import PluginManager from '../auth/pluginmanager';
import ConfigManager from '../configuration/configmanager';
import ErrorManager from '../error/errormanager';
import I18nManager from '../i18n/i18nmanager';
import LayerManager from '../layers/layermanager';
import SnapManager from '../layers/snapmanager';
import LocalFileManager from '../localfile/localfilemanager';
import LogManager from '../logging/logmanager';
import OfflineManager from '../offline/offlinemanager';
import OgcApiFeaturesManager from '../ogcapi/ogcapifeaturesmanager';
import OrderingManager from '../ordering/orderingmanager';
import ISessionManager from '../share/isessionmanager';
import ShareManager from '../share/sharemanager';
import StateSerializer from '../share/stateserializer';
import ComponentManager from '../state/componentManager';
import MapManager from '../state/mapManager';
import StateManager from '../state/statemanager';
import UserInteractionManager from '../state/userInteractionManager';
import CustomThemesManager from '../themes/customthemesmanager';
import ThemesHelper from '../themes/themeshelper';
import ThemesManager from '../themes/themesmanager';
import UserLayerManager from '../themes/userlayermanager';
import PermalinkManager from '../url/permalinkmanager';
import UrlManager from '../url/urlmanager';
import UserDataManager from '../userdata/userdatamanager';
import WfsManager from '../wfs/wfsmanager';
import WmsManager from '../wms/wmsmanager';

export default interface IGirafeContext {
  readonly userDataManager: UserDataManager;
  readonly configManager: ConfigManager;
  readonly stateManager: StateManager;
  readonly componentManager: ComponentManager;
  readonly userInteractionManager: UserInteractionManager;
  readonly i18nManager: I18nManager;
  readonly pluginManager: PluginManager;
  readonly themesManager: ThemesManager;
  readonly themesHelper: ThemesHelper;
  readonly permalinkManager: PermalinkManager;
  readonly urlManager: UrlManager;
  readonly dragManager: DragManager;
  readonly layerManager: LayerManager;
  readonly sessionManager: ISessionManager;
  readonly stateSerializer: StateSerializer;
  readonly shareManager: ShareManager;
  readonly customThemesManager: CustomThemesManager;
  readonly errorManager: ErrorManager;
  readonly wfsManager: WfsManager;
  readonly authManager: AuthManager;
  readonly snapManager: SnapManager;
  readonly mapManager: MapManager;
  readonly logManager: LogManager;
  readonly offlineManager: OfflineManager;
  readonly applicationLifeCycleManager: ApplicationLifeCycleManager;
  readonly orderingManager: OrderingManager;
  readonly userLayerManager: UserLayerManager;
  readonly wmsManager: WmsManager;
  readonly ogcApiFeaturesManager: OgcApiFeaturesManager;
  readonly localFileManager: LocalFileManager;

  initialize(): Promise<void>;
}
