#!/usr/bin/env sh
# ASCII generated with https://patorjk.com/software/taag/#p=display&h=1&v=0&f=Standard&t=GeoGirafe%0A

echo "                                                       "
echo "   ____                ____  _               __        "
echo "  / ___|  ___   ___   / ___|(_) _ __  __ _  / _|  ___  "
echo " | |  _  / _ \ / _ \ | |  _ | || '__|/ _\` || |_  / _ \ "
echo " | |_| ||  __/| (_) || |_| || || |  | (_| ||  _||  __/ "
echo "  \____| \___| \___/  \____||_||_|   \__,_||_|   \___| "
echo "                                                       "
echo "Executing Git pre-commit to keep the girafe beautiful..."
npx lint-staged
